### ISSUE TITLE
Extension doesnt start

### ISSUE THREAD

**Issue by arbadacarbaYK** [DFXswiss/DFXswiss#2]
<img width="731" alt="Screenshot 2023-09-12 at 22 17 34" src="https://github.com/DFXswiss/DFXswiss/assets/63317640/0bfcae5e-614b-477c-b318-455a8de2e138">

**Comment by TaprootFreak** [comment]
Hi @arbadacarbaYK 

Thanks for reporting. We will check tomorrow.

**Comment by TaprootFreak** [comment]
the error is fixed.
